export const ADD_STAFFS = "ADD_STAFFS"
export const ADD_STAFF = "ADD_STAFF"
export const STAFFS_FAILED = "STAFFS_FAILED"
export const DELETE_STAFF = "DELETE_STAFF"
export const UPDATE_STAFF = "UPDATE_STAFF"

export const ADD_DEPARTMENTS = "ADD_DEPARTMENTS"
export const DEPARTMENTS_FAILED = "DEPARTMENTS_FAILED"
