export const LOAD_STAFFS = "LOAD_STAFFS"
export const STAFFS_FAILED = "STAFFS_FAILED"
export const UPDATE_STAFF = "UPDATE_STAFF"

export const LOAD_DEPARTMENTS = "LOAD_DEPARTMENTS"
export const DEPARTMENTS_FAILED = "DEPARTMENTS_FAILED"
